# Importing dependencies


In [4]:
pip install matplotlib


  Using cached matplotlib-3.8.3-cp311-cp311-win_amd64.whl.metadata (5.9 kB)
Using cached matplotlib-3.8.3-cp311-cp311-win_amd64.whl (7.6 MB)
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autoviz 0.1.806 requires nltk, which is not installed.
autoviz 0.1.806 requires seaborn>=0.12.2, which is not installed.
missingno 0.5.2 requires seaborn, which is not installed.
pandas-profiling 3.2.0 requires seaborn>=0.10.1, which is not installed.
ydata-profiling 4.6.5 requires numba<0.59.0,>=0.56.0, which is not installed.
ydata-profiling 4.6.5 requires seaborn<0.13,>=0.10.1, which is not installed.
autoviz 0.1.806 requires matplotlib<=3.7.4, but you have matplotlib 3.8.3 which is incompatible.
autoviz 0.1.806 requires numpy<1.25.0, but you have numpy 1.26.4 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.7.5 which is incompatible.
ydata-profiling 4.6.5 requires numpy<1.26,>=1.16.0, but you have numpy 1.26.4 which is incompatible.
ydata-profiling 

In [6]:
pip install seaborn

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autoviz 0.1.806 requires nltk, which is not installed.
ydata-profiling 4.6.5 requires numba<0.59.0,>=0.56.0, which is not installed.
autoviz 0.1.806 requires matplotlib<=3.7.4, but you have matplotlib 3.8.3 which is incompatible.
autoviz 0.1.806 requires numpy<1.25.0, but you have numpy 1.26.4 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.7.5 which is incompatible.
ydata-profiling 4.6.5 requires numpy<1.26,>=1.16.0, but you have numpy 1.26.4 which is incompatible.
ydata-profiling 4.6.5 requires scipy<1.12,>=1.4.1, but you have scipy 1.12.0 which is incompatible.
ydata-profiling 4.6.5 requires seaborn<0.13,>=0.10.1, but you have seaborn 0.13.2 which is incompatible.


In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

## DATA Ingestion

In [8]:
data= pd.read_csv('creditCardFraud_28011964_120214.csv')
data.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      50000    1          2         1   57     -1      0     -1      0   
1      50000    1          1         2   37      0      0      0      0   
2     500000    1          1         2   29      0      0      0      0   
3     100000    2          2         2   23      0     -1     -1      0   
4     140000    2          3         1   28      0      0      2      0   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0      0  ...      20940      19146      19131      2000     36681     10000   
1      0  ...      19394      19619      20024      2500      1815       657   
2      0  ...     542653     483003     473944     55000     40000     38000   
3      0  ...        221       -159        567       380       601         0   
4      0  ...      12211      11793       3719      3329         0       432   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0      9000       689       679                           0  
1      1000      1000       800                           0  
2     20239     13750     13770                           0  
3       581      1687      1542                           0  
4      1000      1000      1000                           0  

[5 rows x 24 columns]

## Auto EDA

In [9]:
%pip install ydata-profiling

     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.4 kB ? eta -:--:--
     ------------------------- ------------ 41.0/60.4 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 533.6 kB/s eta 0:00:00
  Using cached seaborn-0.12.2-py3-none-any.whl.metadata (5.4 kB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ------ --------------------------------- 0.4/2.6 MB 8.5 MB/s eta 0:00:01
   -------------- ------------------------- 1.0/2.6 MB 10.0 MB/s eta 0:00:01
   -------------------- ------------------- 1.4/2.6 MB 8.7 MB/s eta 0:00:01
   ----------------------- ---------------- 1.6/2.6 MB 7.6 MB/s eta 0:00:01
   ------------------------- -------------- 1.7/2.6 MB 6.7 MB/s eta 0:00:01
   ----------------------------- ---------- 1.9/2.6 MB 6.9 MB/s eta 0:00:01
   -------------------------------- ------- 2.1/2.6 MB 6.4 MB/s eta 0:00:01
   -------------------------

  You can safely remove it manually.
  You can safely remove it manually.
  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
altair 5.2.0 requires toolz, which is not installed.
autoviz 0.1.806 requires nltk, which is not installed.
holoviews 1.14.9 requires colorcet, which is not installed.
holoviews 1.14.9 requires param<2.0,>=1.9.3, which is not installed.
holoviews 1.14.9 requires pyviz-comms>=0.7.4, which is not installed.
hvplot 0.7.3 requires colorcet>=2, which is not installed.
panel 0.14.4 requires bleach, which is not installed.
panel 0.14.4 requires markdown, which is not installed.
panel 0.14.4 requires param>=1.12.0, which is not installed.
panel 0.14.4 requires pyct>=0.4.4, which is not installed.
panel 0.14.4 requires pyviz-comms>=0.7.4, which is not installed.
streamlit 1.30.

In [11]:
pip install ipywidgets


   ---------------------------------------- 0.0/139.4 kB ? eta -:--:--
   ---------------------------------------- 139.4/139.4 kB 8.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/215.0 kB ? eta -:--:--
   ---------------------------------------- 215.0/215.0 kB 6.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.3 MB 9.9 MB/s eta 0:00:01
   ------------- -------------------------- 0.8/2.3 MB 10.0 MB/s eta 0:00:01
   ----------------- ---------------------- 1.0/2.3 MB 9.2 MB/s eta 0:00:01
   ----------------------- ---------------- 1.4/2.3 MB 7.9 MB/s eta 0:00:01
   -------------------------- ------------- 1.5/2.3 MB 6.9 MB/s eta 0:00:01
   --------------------------- ------------ 1.6/2.3 MB 7.1 MB/s eta 0:00:01
   ------------------------------------ --- 2.1/2.3 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 6.4 MB/s eta 0:00:00


In [12]:
from ydata_profiling import ProfileReport
profile = ProfileReport(data , title= 'CreditReport')
profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
data.shape

(1001, 24)

In [ ]:
data.isna().sum()

LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT

In [ ]:
sns.pairplot(data)

'sns.pairplot(data)'

In [ ]:
plt.figure(figsize=(13,8))
sns.heatmap(data.corr(),annot=True)

'plt.figure(figsize=(13,8))\nsns.heatmap(data.corr(),annot=True)'

From the correlation heatmap above, it can be seen that there are some relationships between the feature columns, they are not entirely independent. 

But in this scenario, there is a correlation because a customer who was not able to pay the bill for 1 month was again not able to pay it for the subsequent months and hence the correlation.

Again for the bill amount column, the same has happened. If the customer was not able to pay the bill, then the bill amount almost remained the same, or if the customer was able to pay then the bill amount got reduced.

We remove columns when they convey the same information. But here, dropping the columns shall result in the loss of bill and payment history data. So, we don’t need to drop any column although there is a correlation. 


# Spliting dependent and independent of features

In [ ]:
X = data.drop(labels=['default payment next month'], axis=1)
y= data['default payment next month']

In [ ]:
X.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [ ]:
X.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      50000    1          2         1   57     -1      0     -1      0   
1      50000    1          1         2   37      0      0      0      0   
2     500000    1          1         2   29      0      0      0      0   
3     100000    2          2         2   23      0     -1     -1      0   
4     140000    2          3         1   28      0      0      2      0   

   PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0      0  ...      35835      20940      19146      19131      2000     36681   
1      0  ...      57608      19394      19619      20024      2500      1815   
2      0  ...     445007     542653     483003     473944     55000     40000   
3      0  ...        601        221       -159        567       380       601   
4      0  ...      12108      12211      11793       3719      3329         0   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0     10000      9000       689       679  
1       657      1000      1000       800  
2     38000     20239     13750     13770  
3         0       581      1687      1542  
4       432      1000      1000      1000  

[5 rows x 23 columns]

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: default payment next month, dtype: int64

# Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33 , random_state=42)

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
scaled_train_data = scaler.fit_transform(X_train)
scaled_test_data = scaler.transform(X_test)

In [ ]:
type(scaled_train_data) , type(X)

(numpy.ndarray, pandas.core.frame.DataFrame)

# Model Training

Gaussian Naive Baye's

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
def metrics(y_true , y_predicted):
    ac=accuracy_score(y_true,y_predicted)
    cm=confusion_matrix(y_true,y_predicted)
    cr=classification_report(y_true,y_predicted)
    return print("Accuracy_score is:-  {0} \n----------------------------------\n Confusion_matrix is:- \n {1} \n-----------------------------------\n Classification_report is:-\n {2}".format(ac,cm,cr))

def get_difference(y_true , y_predicted , y_predicted_cv):
    as1 = accuracy_score(y_true , y_predicted_cv)
    as2 = accuracy_score(y_true , y_predicted)
    diff= as1-as2 
    return print("Model is performing:- {:.2f} % better \n Without CV accuracy:- {:.2f} % \n After CV accuracy:- {:.2f} %".format(diff*100,as2*100 ,as1*100 ))
    #return diff


In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
y_pred=gnb.fit(scaled_train_data,y_train).predict(scaled_test_data)
metrics(y_test , y_pred)

Accuracy_score is:-  0.676737160120846 
----------------------------------
 Confusion_matrix is:- 
 [[188  83]
 [ 24  36]] 
-----------------------------------
 Classification_report is:-
               precision    recall  f1-score   support

           0       0.89      0.69      0.78       271
           1       0.30      0.60      0.40        60

    accuracy                           0.68       331
   macro avg       0.59      0.65      0.59       331
weighted avg       0.78      0.68      0.71       331



Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
y_pred1=rf.fit(scaled_train_data,y_train).predict(scaled_test_data)
metrics(y_test , y_pred1)

Accuracy_score is:-  0.8459214501510574 
----------------------------------
 Confusion_matrix is:- 
 [[263   8]
 [ 43  17]] 
-----------------------------------
 Classification_report is:-
               precision    recall  f1-score   support

           0       0.86      0.97      0.91       271
           1       0.68      0.28      0.40        60

    accuracy                           0.85       331
   macro avg       0.77      0.63      0.66       331
weighted avg       0.83      0.85      0.82       331



XG Boost Classifier

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
y_pred2 = xgb.fit(scaled_train_data,y_train).predict(scaled_test_data)
metrics(y_test , y_pred2)

Accuracy_score is:-  0.8126888217522659 
----------------------------------
 Confusion_matrix is:- 
 [[248  23]
 [ 39  21]] 
-----------------------------------
 Classification_report is:-
               precision    recall  f1-score   support

           0       0.86      0.92      0.89       271
           1       0.48      0.35      0.40        60

    accuracy                           0.81       331
   macro avg       0.67      0.63      0.65       331
weighted avg       0.79      0.81      0.80       331



# Model Evaluation
<h3>Hyperparameter Tuning

1) Gaussian Naive Baye's

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid={'var_smoothing':[ 1e-12,1e-10,1e-6,1e-4,1e-3,1e-2,1e-1,0.1,0.001,0.5,0.005]}
grid=GridSearchCV(estimator=gnb,param_grid=param_grid,cv=5,verbose=3)
grid.fit(scaled_train_data,y_train)
grid.best_params_

Fitting 5 folds for each of 11 candidates, totalling 55 fits
[CV 1/5] END ...............var_smoothing=1e-12;, score=0.299 total time=   0.0s
[CV 2/5] END ...............var_smoothing=1e-12;, score=0.769 total time=   0.0s
[CV 3/5] END ...............var_smoothing=1e-12;, score=0.694 total time=   0.0s
[CV 4/5] END ...............var_smoothing=1e-12;, score=0.679 total time=   0.0s
[CV 5/5] END ...............var_smoothing=1e-12;, score=0.679 total time=   0.0s
[CV 1/5] END ...............var_smoothing=1e-10;, score=0.299 total time=   0.0s
[CV 2/5] END ...............var_smoothing=1e-10;, score=0.769 total time=   0.0s
[CV 3/5] END ...............var_smoothing=1e-10;, score=0.694 total time=   0.0s
[CV 4/5] END ...............var_smoothing=1e-10;, score=0.679 total time=   0.0s
[CV 5/5] END ...............var_smoothing=1e-10;, score=0.679 total time=   0.0s
[CV 1/5] END ...............var_smoothing=1e-06;, score=0.299 total time=   0.0s
[CV 2/5] END ...............var_smoothing=1e-06;

{'var_smoothing': 0.5}

In [ ]:
gnb_cv = GaussianNB(var_smoothing=0.5)
y_pred_cv=gnb_cv.fit(scaled_train_data,y_train).predict(scaled_test_data)
metrics(y_test , y_pred_cv)

Accuracy_score is:-  0.8066465256797583 
----------------------------------
 Confusion_matrix is:- 
 [[243  28]
 [ 36  24]] 
-----------------------------------
 Classification_report is:-
               precision    recall  f1-score   support

           0       0.87      0.90      0.88       271
           1       0.46      0.40      0.43        60

    accuracy                           0.81       331
   macro avg       0.67      0.65      0.66       331
weighted avg       0.80      0.81      0.80       331



In [ ]:
get_difference(y_test , y_pred , y_pred_cv)

Model is performing:- 12.99 % better 
 Without CV accuracy:- 67.67 % 
 After CV accuracy:- 80.66 %


2) Random Forest Classifier

In [ ]:
param_grid1= {"n_estimators":[100,50,150], "criterion":['gini','entropy','log_loss'], 'max_depth':[1,3,9,15],'max_features':['sqrt','log2'],'oob_score':[True,False], 'class_weight':['balanced','balanced_subsample'],'random_state':[0,50,42] }
grid=GridSearchCV(estimator=rf,param_grid=param_grid1,cv=5,verbose=3)
grid.fit(scaled_train_data,y_train)
grid.best_params_

'param_grid1= {"n_estimators":[100,50,150], "criterion":[\'gini\',\'entropy\',\'log_loss\'], \'max_depth\':[1,3,9,15],\'max_features\':[\'sqrt\',\'log2\'],\'oob_score\':[True,False], \'class_weight\':[\'balanced\',\'balanced_subsample\'],\'random_state\':[0,50,42] }\ngrid=GridSearchCV(estimator=rf,param_grid=param_grid1,cv=5,verbose=3)\ngrid.fit(scaled_train_data,y_train)\ngrid.best_params_'

{'class_weight': 'balanced_subsample',
 'criterion': 'gini',
 'max_depth': 9,
 'max_features': 'sqrt',
 'n_estimators': 50,
 'oob_score': True,
 'random_state': 42}

In [ ]:
rf_cv1_1 = RandomForestClassifier(class_weight='balanced_subsample', criterion='gini', max_depth= 9,max_features= 'sqrt',n_estimators=100,oob_score=True,random_state=0)
y_pred_cv1_1=rf_cv1_1.fit(scaled_train_data,y_train).predict(scaled_test_data)
metrics(y_test , y_pred_cv1_1)

Accuracy_score is:-  0.8398791540785498 
----------------------------------
 Confusion_matrix is:- 
 [[258  13]
 [ 40  20]] 
-----------------------------------
 Classification_report is:-
               precision    recall  f1-score   support

           0       0.87      0.95      0.91       271
           1       0.61      0.33      0.43        60

    accuracy                           0.84       331
   macro avg       0.74      0.64      0.67       331
weighted avg       0.82      0.84      0.82       331



In [ ]:
get_difference(y_test , y_pred1 , y_pred_cv1_1)

Model is performing:- -0.60 % better 
 Without CV accuracy:- 84.59 % 
 After CV accuracy:- 83.99 %


Let's tweek few more parameters to see if we can further improve the accuracy

In [ ]:
param_grid1= {"n_estimators":[100,50,75], "criterion":['gini','entropy'],'max_features':['sqrt'],'oob_score':[True],'random_state':[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39] }
grid=GridSearchCV(estimator=rf,param_grid=param_grid1,cv=5,verbose=3)
grid.fit(scaled_train_data,y_train)
grid.best_params_

Fitting 5 folds for each of 84 candidates, totalling 420 fits
[CV 1/5] END criterion=gini, max_features=sqrt, n_estimators=100, oob_score=True, random_state=0;, score=0.776 total time=   0.5s
[CV 2/5] END criterion=gini, max_features=sqrt, n_estimators=100, oob_score=True, random_state=0;, score=0.761 total time=   0.5s
[CV 3/5] END criterion=gini, max_features=sqrt, n_estimators=100, oob_score=True, random_state=0;, score=0.754 total time=   0.5s
[CV 4/5] END criterion=gini, max_features=sqrt, n_estimators=100, oob_score=True, random_state=0;, score=0.769 total time=   0.3s
[CV 5/5] END criterion=gini, max_features=sqrt, n_estimators=100, oob_score=True, random_state=0;, score=0.746 total time=   0.3s
[CV 1/5] END criterion=gini, max_features=sqrt, n_estimators=100, oob_score=True, random_state=3;, score=0.776 total time=   0.3s
[CV 2/5] END criterion=gini, max_features=sqrt, n_estimators=100, oob_score=True, random_state=3;, score=0.776 total time=   0.3s
[CV 3/5] END criterion=gini,

{'criterion': 'entropy',
 'max_features': 'sqrt',
 'n_estimators': 50,
 'oob_score': True,
 'random_state': 12}

In [ ]:
rf_cv = RandomForestClassifier(class_weight='balanced_subsample', criterion='entropy', max_depth= 9,max_features= 'sqrt',n_estimators=50,oob_score=True,random_state=0)
y_pred_cv1=rf_cv.fit(scaled_train_data,y_train).predict(scaled_test_data)
metrics(y_test , y_pred_cv1)

Accuracy_score is:-  0.8549848942598187 
----------------------------------
 Confusion_matrix is:- 
 [[260  11]
 [ 37  23]] 
-----------------------------------
 Classification_report is:-
               precision    recall  f1-score   support

           0       0.88      0.96      0.92       271
           1       0.68      0.38      0.49        60

    accuracy                           0.85       331
   macro avg       0.78      0.67      0.70       331
weighted avg       0.84      0.85      0.84       331



In [ ]:
get_difference(y_test , y_pred1 , y_pred_cv1)

Model is performing:- 0.91 % better 
 Without CV accuracy:- 84.59 % 
 After CV accuracy:- 85.50 %


3) XG Boost Classifier 

In [ ]:
param_grid2={'max_depth': range(3, 11),
                         'n_estimators': [50, 100, 130, 200],
                         'random_state': [0, 50, 100, 250, 355, 500]}
grid= GridSearchCV(XGBClassifier(objective='binary:logistic'),param_grid2, cv=5,n_jobs=-1)
grid.fit(scaled_train_data,y_train)
grid.best_params_

{'max_depth': 5, 'n_estimators': 200, 'random_state': 0}

In [ ]:
xgb_new=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, n_estimators=50, n_jobs=-1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1,missing=np.nan)

pred_y_xgb_new = xgb_new.fit(scaled_train_data,y_train).predict(scaled_test_data)
metrics(y_test , pred_y_xgb_new)


Accuracy_score is:-  0.8308157099697885 
----------------------------------
 Confusion_matrix is:- 
 [[262   9]
 [ 47  13]] 
-----------------------------------
 Classification_report is:-
               precision    recall  f1-score   support

           0       0.85      0.97      0.90       271
           1       0.59      0.22      0.32        60

    accuracy                           0.83       331
   macro avg       0.72      0.59      0.61       331
weighted avg       0.80      0.83      0.80       331



In [ ]:
get_difference(y_test , y_pred2 , pred_y_xgb_new)

Model is performing:- 1.81 % better 
 Without CV accuracy:- 81.27 % 
 After CV accuracy:- 83.08 %
